hw_11
myKilin/hillelPRO pull request #6
Opened 2022-11-19 10:09 UTC by myKilin

2022-11-19 13:50 UTC, vb-oiko commented on hw_11/index.js
> +// console.log(resalt);
тут потрібно було вивести довжину масива а не сам масив

2022-11-19 13:51 UTC, vb-oiko commented on hw_11/index.js
> +// console.log(resalt);
те саме що і вище

2022-11-19 13:53 UTC, vb-oiko commented on hw_11/index.js
> +
Ви створюєте новий масив згідно вимогам завдання, а потрібно було робити зміни у самому вхідному масиві

2022-11-19 13:54 UTC, vb-oiko requested changes
будь ласка виправте зауваження

2022-11-20 17:34 UTC, myKilin commented on hw_11/index.js
> +
Змінив

2022-11-21 11:38 UTC, myKilin commented
Виправив

On Sat, Nov 19, 2022, 15:54 Vasyl Boyko ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> будь ласка виправте зауваження
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/myKilin/hillelPRO/pull/6#pullrequestreview-1187074355>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZPZYQLWPZVUIPQ3OI4YX63WJDL2HANCNFSM6AAAAAASFHSPQ4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-21 15:52 UTC, vb-oiko commented on hw_11/index.js
> +//   if(!(arr[i] === arr1)) {
```suggestion
//   if(arr[i] !== arr1) {
```

так краще читатиметься

2022-11-21 15:53 UTC, vb-oiko approved these changes
Здайте домашку у системі, я без цього не можу виставити іншу оцінку

2022-11-21 16:00 UTC, merged